### ISSUE TITLE
encoding issue?

### ISSUE THREAD

**Issue by EKE00372** [Oppzippy/GlobalSearch#32]
for example searching 炉石(hearthstone) and show 爆裂熔炉(Blast Furnace) as related
![image](https://github.com/Oppzippy/GlobalSearch/assets/1412472/1dfa01ad-be8c-4ea6-a962-e64156d324ec)
![image](https://github.com/Oppzippy/GlobalSearch/assets/1412472/b220d10c-ddfc-4648-8215-7591dcd39e79)

**Comment by Oppzippy** [comment]
This is probably an issue with Korean and Russian as well. Unfortunately, there's no easy solution to this, since the version of Lua that WoW uses does not support UTF8. There are some UTF8 libraries, but I doubt the performance would be sufficient when UTF8 functions are implemented in pure Lua when compared to the standard library's C implementation.

Another issue with Chinese is that determining word boundaries is a lot more complicated due to the lack of spaces. In addition to the main search that works per character, GlobalSearch also searches by word, including text in tooltips, and orders the results by the number of matching words. I guess for Chinese, it could go by number of marching characters rather than words, and while not ideal, it may work okay in practice.

I'll probably look into this at some point, but since it's possible that there is no good solution, I'm not really motivated to prioritize this.

**Comment by Oppzippy** [comment]
I ran some benchmarks and it turns out I vastly overestimated how fast `string.find` is compared to a for loop, so this should actually be doable.

**Comment by Oppzippy** [comment]
Please give the latest alpha version a try and let me know if you encounter any issues.

**Comment by EKE00372** [comment]
version v0.22.9-3-gedfa66d
works fine

version v0.22.9-11-gf1d6aea
`AddOns/GlobalSearch/Internal/Unicode/UTF8.lua:33: bad argument #1 to 'band' (number expected, got nil)`

**Comment by Oppzippy** [comment]
> `AddOns/GlobalSearch/Internal/Unicode/UTF8.lua:33: bad argument #1 to 'band' (number expected, got nil)`

Should be fixed as of d0f031339b91f3d96d17468ea686981449413529. If you can confirm it's working for you now, I'll go ahead and do a release.

**Comment by EKE00372** [comment]
It works fine now.

**Comment by Oppzippy** [comment]
No, I just forgot to put the strings on curseforge. They're added now. Thanks.
